cue: both run and uses are required
`cue vet` now works, However, the workflows do not:

```text
Error: .github#L1
a step cannot have both the `uses` and `run` keys
```